const CANCER_CODES = Object.freeze(
  new Set([
    "blca",
    "brca",
    "cesc",
    "coad",
    "esca",
    "gbm",
    "hnsc",
    "kich",
    "kirc",
    "lgg",
    "lihc",
    "luad",
    "lusc",
    "ov",
    "paad",
    "pcpg",
    "prad",
    "read",
    "sarc",
    "skcm",
    "stad",
    "tgct",
    "thca",
    "ucec",
    "gtex",
  ]),
);

const CANCER_NAMES = Object.freeze({
  blca: "Bladder Urothelial Carcinoma",
  brca: "Breast Invasive Carcinoma",
  cesc: "Cervical & Endocervical Cancer",
  coad: "Colon Adenocarcinoma",
  esca: "Esophageal Carcinoma",
  gbm: "Glioblastoma Multiforme",
  hnsc: "Head & Neck Squamous Cell Carcinoma",
  kich: "Kidney Chromophobe",
  kirc: "Kidney Renal Clear Cell Carcinoma",
  lgg: "Brain Lower Grade Glioma",
  lihc: "Liver Hepatocellular Carcinoma",
  luad: "Lung Adenocarcinoma",
  lusc: "Lung Squamous Cell Carcinoma",
  ov: "Ovarian Serous Cystadenocarcinoma",
  paad: "Pancreatic Adenocarcinoma",
  pcpg: "Pheochromocytoma & Paraganglioma",
  prad: "Prostate Adenocarcinoma",
  read: "Rectum Adenocarcinoma",
  sarc: "Sarcoma",
  skcm: "Skin Cutaneous Melanoma",
  stad: "Stomach Adenocarcinoma",
  tgct: "Testicular Germ Cell Tumors",
  thca: "Thyroid Carcinoma",
  ucec: "Uterine Corpus Endometrial Carcinoma",
  gtex: "GTEx Normal Tissue Reference",
});

module.exports = { CANCER_CODES, CANCER_NAMES };